name: Android CI
# from https://medium.com/@wkrzywiec/github-actions-for-android-first-approach-f616c24aa0f9

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Loading secrets
        run: |
          # not yet needed echo $gservices > ./app/google-services.json
          rm ./app/google-services.json          
          cp ./app/google-services-example.json ./app/google-services.json
          rm ./app/src/main/res/values/mapbox-token.xml
          cp ./app/special/mapbox-token.xml ./app/src/main/res/values/
          # The following would not be valid XML, don't use yet
          # echo $MAPBOXTOKEN > ./app/src/main/res/values/mapbox-token.xml
          mkdir -p ~/.gradle
          echo "MAPBOX_DOWNLOADS_TOKEN=$MAPBOXTOKEN" >>~/.gradle/gradle.properties
        env:
          gservices: ${{ secrets.gservices }}
          MAPBOXTOKEN: ${{ secrets.MAPBOXTOKEN }}
      - name: Mock curfirmware version for CI
        run: |
          rm ./app/src/main/res/values/curfirmwareversion.xml
          cp ./app/special/curfirmwareversion.xml ./app/src/main/res/values/
      - name: set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 16
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
        
